# Generated by Django 4.2.20 on 2025-04-22 06:26

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(blank=True, default=authentication.models.get_default_admin, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
