# Generated by Django 4.2.20 on 2025-04-23 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_referral_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=False)),
                ('wallet', models.IntegerField(default=0)),
                ('owener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
