# Generated by Django 4.2.20 on 2025-04-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customerpool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpool',
            old_name='owener',
            new_name='owner',
        ),
    ]
