# Generated by Django 4.2.20 on 2025-04-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_owener_customerpool_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
