# Generated by Django 4.2.20 on 2025-04-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customerpool_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='flat_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='locality',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
