# Generated by Django 4.2.20 on 2025-04-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_address_line_2_address_flat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_mode',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('others', 'Others')], default='home', help_text='modes of address', max_length=15),
        ),
    ]
