# Generated by Django 4.2.20 on 2025-05-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_address_address_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpool',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
