# Generated by Django 4.2.20 on 2025-05-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customerpool_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpool',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
