# Generated by Django 4.2.20 on 2025-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='global_pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BigIntegerField(default=1)),
                ('end', models.BigIntegerField(default=1)),
                ('pool_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('total_window_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
    ]
