# Generated by Django 4.2.20 on 2025-04-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_global_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_pool',
            name='latest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='global_pool',
            name='end',
            field=models.BigIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='global_pool',
            name='start',
            field=models.BigIntegerField(default=2),
        ),
    ]
