# Generated by Django 4.2.20 on 2025-04-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_global_pool_latest_alter_global_pool_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_pool',
            name='end',
            field=models.BigIntegerField(default=1),
        ),
    ]
